# Site settings
title: Marcy Blog
SEOTitle: Marcy Blog
header-img: img/home-bg.jpg
email: marcyliew@gmail.com
description: "Software Engineer，Focus on Backend, but could do full stack | Just a blog to share tech notes, and thoughts"
keyword: "Software Engineer"
url: "marcyliao.me"
baseurl: ""



# SNS settings
RSS: false
github_username:    mxliao
linkedin_username:  mengxi-liao-0285397b



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: marcyliao-me

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'xxx'            # Format: UA-xxxxxx-xx
ga_domain: xxx



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "A coder and a father"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
# friends: [
    # {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{

    # }
# ]
